version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      expo-and-react-native:
        patterns:
          - expo
          - expo-*
          - react
          - react-dom
          - react-native
          - react-native-*
      remaining-dependencies:
        patterns:
          - '*'
