import { StyleSheet } from 'react-native';
import { palette } from '../constants/colors';

export const createStyles = (theme, compact = false) => StyleSheet.create({
  cancelButton: { alignItems: 'center', alignSelf: 'center', justifyContent: 'center', minHeight: 44, paddingHorizontal: 16 },
  cancelText: { color: theme.error, fontFamily: 'Inter-SemiBold', fontSize: 13 },
  catalogItem: { borderBottomColor: theme.border, borderBottomWidth: 1, gap: 5, paddingVertical: 14 },
  catalogName: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 15 },
  content: { alignSelf: 'center', maxWidth: 640, paddingBottom: 32, paddingHorizontal: compact ? 10 : 20, width: '100%' },
  disabled: { opacity: 0.5 },
  empty: { alignItems: 'center', flex: 1, gap: 12, justifyContent: 'center', padding: 28 },
  emptyTitle: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 22 },
  exerciseCount: { color: theme.textSecondary, fontFamily: 'Inter-SemiBold', fontSize: 14, marginTop: 7 },
  exerciseList: { gap: 10 },
  eyebrow: { color: theme.primary, fontFamily: 'Inter-Bold', fontSize: 11, letterSpacing: 1.4 },
  finishButton: { alignItems: 'center', borderColor: theme.textSecondary, borderRadius: 10, borderWidth: 1, justifyContent: 'center', marginTop: 14, minHeight: 48 },
  finishDisabled: { borderColor: theme.border, opacity: 0.55 },
  finishText: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 16 },
  finishTextDisabled: { color: theme.textSecondary },
  header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 58 },
  headerButton: { alignItems: 'center', justifyContent: 'center', minHeight: 44, width: 44 },
  headerTitle: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: compact ? 14 : 15 },
  link: { color: theme.primary, fontFamily: 'Inter-SemiBold', fontSize: 14 },
  modalActions: { flexDirection: 'row', gap: 10 },
  muted: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 13 },
  notes: { borderColor: theme.border, borderRadius: 10, borderWidth: 1, color: theme.textPrimary, fontFamily: 'Inter', minHeight: 76, padding: 12, textAlignVertical: 'top' },
  pausedLabel: { color: theme.secondary, fontFamily: 'Inter-SemiBold', fontSize: 12, marginTop: 10, textAlign: 'center' },
  pickerContent: { padding: 18 },
  pickerHeader: { alignItems: 'center', borderBottomColor: theme.border, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: 16 },
  primaryButton: { alignItems: 'center', backgroundColor: theme.primary, borderRadius: 10, flex: 1, justifyContent: 'center', minHeight: 48, paddingHorizontal: 14 },
  primaryButtonText: { color: palette.whitePure, fontFamily: 'Inter-Bold', fontSize: 14 },
  programHeader: { marginBottom: 10, marginTop: 26 },
  programTitle: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: compact ? 18 : 19 },
  programTitleBlock: { flex: 1 },
  result: { alignSelf: 'center', gap: 16, maxWidth: 600, padding: 22, width: '100%' },
  resultCard: { backgroundColor: theme.cardBackground, borderColor: theme.border, borderRadius: 14, borderWidth: 1, gap: 13, padding: 16 },
  resultRow: { flexDirection: 'row', justifyContent: 'space-between' },
  resultValue: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 14 },
  resumeAction: { backgroundColor: palette.greenBright },
  safe: { backgroundColor: theme.background, flex: 1 },
  saveForm: { gap: 14, padding: 20 },
  secondaryButton: { alignItems: 'center', borderColor: theme.primary, borderRadius: 10, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 48, paddingHorizontal: 14 },
  secondaryButtonText: { color: theme.primary, fontFamily: 'Inter-Bold', fontSize: 14 },
  sectionTitle: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 18 },
  timerAction: { alignItems: 'center', alignSelf: 'center', backgroundColor: theme.primary, borderRadius: 12, flexDirection: 'row', gap: 8, justifyContent: 'center', minHeight: 58, minWidth: compact ? 150 : 166, paddingHorizontal: 20 },
  timerActionText: { color: palette.whitePure, fontFamily: 'Inter-Bold', fontSize: compact ? 18 : 20 },
  timerValue: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: compact ? 35 : 39, fontVariant: ['tabular-nums'], marginBottom: 14, marginTop: 8, textAlign: 'center' },
  title: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 27 },
  workoutNotes: { marginTop: 14 },
});
