import { Platform, StyleSheet } from 'react-native';

export const createStyles = (theme) => StyleSheet.create({
  safeArea: { backgroundColor: theme.background, flex: 1 },
  content: { alignSelf: 'center', maxWidth: 620, padding: 20, paddingBottom: 50, width: '100%' },
  header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 22 },
  backButton: { alignItems: 'center', height: 36, justifyContent: 'center', width: 36 },
  title: { color: theme.textPrimary, fontSize: 18, fontWeight: '900' },
  hint: { color: theme.textSecondary, fontSize: 13, marginBottom: 18 },
  field: { marginBottom: 15 },
  label: { color: theme.textSecondary, fontSize: 13, fontWeight: '700', marginBottom: 7 },
  input: { backgroundColor: theme.cardBackground, borderColor: theme.border, borderRadius: 10, borderWidth: 1, color: theme.textPrimary, fontSize: 16, minHeight: 46, paddingHorizontal: 13, ...Platform.select({ web: { outlineStyle: 'none' }, default: {} }) },
  inputFocused: { borderColor: theme.primary },
  dateButton: { alignItems: 'center', backgroundColor: theme.cardBackground, borderColor: theme.border, borderRadius: 10, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 46, paddingHorizontal: 13 },
  dateText: { color: theme.textPrimary, fontSize: 15 },
  error: { color: theme.error, fontSize: 13, lineHeight: 19, marginTop: 14 },
  submit: { alignItems: 'center', backgroundColor: theme.primary, borderRadius: 11, justifyContent: 'center', marginTop: 24, minHeight: 48 },
  submitText: { color: theme.onPrimary, fontSize: 16, fontWeight: '800' },
  disabled: { opacity: 0.45 },
  interactive: { opacity: 0.82 },
  pressed: { opacity: 0.65 },
  overlay: { alignItems: 'center', backgroundColor: theme.overlay, flex: 1, justifyContent: 'center', padding: 18 },
  calendarModal: { backgroundColor: theme.cardBackground, borderRadius: 20, maxWidth: 430, padding: 18, width: '100%' },
  calendarTitle: { color: theme.textPrimary, fontSize: 19, fontWeight: '900', textAlign: 'center' },
  monthHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  monthArrow: { alignItems: 'center', height: 40, justifyContent: 'center', width: 40 },
  monthTitle: { color: theme.textPrimary, fontSize: 16, fontWeight: '800', textTransform: 'capitalize' },
  weekHeader: { flexDirection: 'row', marginTop: 4 },
  weekLabel: { color: theme.textSecondary, fontSize: 11, fontWeight: '700', textAlign: 'center', width: '14.285%' },
  monthGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 5 },
  monthDay: { alignItems: 'center', height: 43, justifyContent: 'center', width: '14.285%' },
  monthDayText: { color: theme.textPrimary, fontSize: 13, fontWeight: '700' },
  activeDayText: { backgroundColor: theme.primary, borderRadius: 16, color: theme.onPrimary, overflow: 'hidden', paddingHorizontal: 9, paddingVertical: 6 },
  closeButton: { alignItems: 'center', borderColor: theme.border, borderRadius: 10, borderWidth: 1, marginTop: 15, padding: 11 },
  cancelText: { color: theme.textPrimary, fontSize: 13, fontWeight: '800' },
});
