import { StyleSheet } from 'react-native';

import { palette } from '../constants/colors';
export const createStyles = (theme) => StyleSheet.create({
  headingGroup: { gap: 6 },
  usersSection: { gap: 20 },
  searchField: { flex: 1, minWidth: 160 },
  center: { justifyContent: "center", alignItems: "center", padding: 24 },
  page: {
    padding: 20,
    paddingBottom: 40,
    width: "100%",
    maxWidth: 1240,
    alignSelf: "center",
    gap: 28,
  },
  top: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 20,
    paddingTop: 16,
  },
  brand: {
    color: palette.accent,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 2,
  },
  title: { color: theme.textPrimary, fontSize: 32, fontWeight: "700" },
  identity: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    backgroundColor: theme.cardBackground,
    padding: 12,
    borderRadius: 10,
  },
  topActions: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", gap: 10 },
  dot: { width: 7, height: 7, borderRadius: 4 },
  tabs: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    gap: 8,
  },
  tab: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 3,
    borderBottomColor: palette.transparent,
  },
  activeTab: { borderBottomColor: palette.accent, backgroundColor: palette.accentWash },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 16 },
  userCard: {
    flexBasis: 300,
    flexGrow: 1,
    backgroundColor: theme.cardBackground,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 16,
    padding: 18,
    gap: 12,
  },
  userCardPressed: { opacity: 0.82, borderColor: theme.primary },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.accentTint,
  },
  avatarText: { color: palette.redSoft, fontWeight: "700", fontSize: 16 },
  roleBadge: {
    borderWidth: 1,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  presence: { flexDirection: "row", alignItems: "center", gap: 6 },
  cardBottom: {
    borderTopWidth: 1,
    borderTopColor: theme.border,
    paddingTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
});
