import { StyleSheet } from 'react-native';

export const createStyles = (theme) => StyleSheet.create({
  screen: { backgroundColor: theme.background, flex: 1 },
  content: { alignSelf: 'center', gap: 10, maxWidth: 800, paddingBottom: 34, paddingHorizontal: 20, paddingTop: 8, width: '100%' },
  header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  backButton: { alignItems: 'center', height: 40, justifyContent: 'center', width: 40 },
  title: { color: theme.textPrimary, flex: 1, fontFamily: 'Inter-Bold', fontSize: 15, textAlign: 'center' },
  loader: { marginTop: 70 },
  sectionTitle: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 13 },
  summaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  summaryCard: { alignItems: 'center', backgroundColor: theme.cardBackground, borderRadius: 9, flexBasis: '48%', flexGrow: 1, gap: 5, justifyContent: 'center', minHeight: 72, padding: 10 },
  summaryLabel: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 11 },
  summaryValue: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 17 },
  card: { backgroundColor: theme.cardBackground, borderRadius: 10, gap: 8, overflow: 'hidden', padding: 12 },
  chartBox: { overflow: 'hidden', width: '100%' },
  cardTitle: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 13 },
  muted: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 10, lineHeight: 15 },
  detail: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 10 },
  retry: { color: theme.primary, fontFamily: 'Inter-Bold', fontSize: 13, paddingVertical: 10 },
  axisText: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 8 },
  detailGrid: { alignItems: 'stretch', flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  halfCard: { flex: 1, minWidth: 150, overflow: 'hidden' },
  rangeRow: { flexDirection: 'row', justifyContent: 'space-between' },
  tooltip: { borderColor: theme.textSecondary, borderRadius: 4, borderWidth: 1, gap: 2, padding: 5 },
  tooltipText: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 9 },
  cta: { alignItems: 'center', backgroundColor: theme.primary, borderRadius: 11, justifyContent: 'center', minHeight: 46 },
  ctaText: { color: theme.onPrimary, fontFamily: 'Inter-SemiBold', fontSize: 14 },
});
