import { StyleSheet } from 'react-native';

export const createStyles = (theme) => StyleSheet.create({
  screen: { backgroundColor: theme.background, flex: 1 },
  content: { alignSelf: 'center', gap: 10, maxWidth: 800, paddingBottom: 44, paddingHorizontal: 20, paddingTop: 18, width: '100%' },
  pageLoader: { flex: 1 },
  title: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 16, marginBottom: 7 },
  card: { backgroundColor: theme.cardBackground, borderRadius: 10, gap: 7, padding: 12 },
  topRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  planCard: { flexBasis: 150, flexGrow: 0.85, minHeight: 96, minWidth: 140 },
  activityCard: { flexBasis: 180, flexGrow: 1.15, minHeight: 96, minWidth: 150 },
  cardHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  cardTitle: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 13 },
  inline: { alignItems: 'baseline', flexDirection: 'row' },
  hero: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 25 },
  percent: { color: theme.primary, fontFamily: 'Inter-Bold', fontSize: 16, marginLeft: 'auto' },
  accentText: { color: theme.primary, fontFamily: 'Inter-SemiBold' },
  muted: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 11, lineHeight: 16 },
  micro: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 10 },
  retry: { alignSelf: 'flex-start', justifyContent: 'center', minHeight: 40 },
  retryText: { color: theme.primary, fontFamily: 'Inter-Bold', fontSize: 13 },
  activityChart: { alignItems: 'flex-end', flexDirection: 'row', gap: 8, height: 58, justifyContent: 'space-around' },
  activityColumn: { alignItems: 'center', gap: 3 },
  activityPlanned: { backgroundColor: theme.textSecondary, borderRadius: 2, justifyContent: 'flex-end', minHeight: 2, overflow: 'hidden', width: 13 },
  activityDone: { backgroundColor: theme.primary, width: '100%' },
  chartLabel: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 8 },
  summaryRow: { flexDirection: 'row' },
  summaryItem: { flex: 1, gap: 5, minWidth: 0, paddingHorizontal: 7 },
  summaryBorder: { borderLeftColor: theme.border, borderLeftWidth: 1 },
  summaryLabel: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 10 },
  summaryValue: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 18 },
  unit: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 10 },
  intensityRow: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', minHeight: 88 },
  bandRow: { flexDirection: 'row', gap: 14 },
  band: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 11 },
  bandValue: { color: theme.textPrimary, fontFamily: 'Inter-Bold' },
  muscleRow: { alignItems: 'center', flexDirection: 'row', gap: 8, minHeight: 18 },
  muscleName: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 11, width: 62 },
  muscleTrack: { backgroundColor: theme.border, borderRadius: 4, flex: 1, height: 7, overflow: 'hidden' },
  muscleFill: { backgroundColor: theme.primary, borderRadius: 4, height: 7 },
  muscleCount: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 10, textAlign: 'right', width: 24 },
  strengthRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 20 },
  strengthName: { color: theme.textPrimary, flex: 1, fontFamily: 'Inter', fontSize: 11 },
  delta: { color: theme.secondary, fontFamily: 'Inter-SemiBold', fontSize: 10 },
  link: { color: theme.secondary, fontFamily: 'Inter-SemiBold', fontSize: 11, marginTop: 3 },
  bodyRow: { flexDirection: 'row' },
  bodyRowNarrow: { flexWrap: 'wrap', rowGap: 10 },
  bodyItem: { flex: 1, gap: 5, minWidth: 0, paddingHorizontal: 7 },
  bodyItemNarrow: { flexBasis: '50%', flexGrow: 0, minWidth: '50%' },
  bodyItemLower: { borderTopColor: theme.border, borderTopWidth: 1, paddingTop: 10 },
  bodyValue: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 16 },
  insightRow: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  insight: { color: theme.textPrimary, flex: 1, fontFamily: 'Inter', fontSize: 11, lineHeight: 16 },
  todayProgramRow: { alignItems: 'center', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  todayProgramCopy: { flex: 1, gap: 5, justifyContent: 'center', minHeight: 50 },
  todayProgramName: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 17, lineHeight: 22 },
  completionBadge: { backgroundColor: theme.success, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 5 },
  completionBadgeText: { color: theme.onPrimary, fontFamily: 'Inter-Bold', fontSize: 10 },
  todayMetrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  todayMetricCard: { backgroundColor: theme.cardBackground, borderRadius: 10, flexBasis: 78, flexGrow: 1, gap: 5, maxWidth: 190, minHeight: 92, minWidth: 78, padding: 10 },
  todayMetricValue: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 17 },
  todayBars: { alignItems: 'flex-end', flexDirection: 'row', gap: 12, height: 64, justifyContent: 'center' },
  todayBarColumn: { alignItems: 'center', gap: 3, justifyContent: 'flex-end' },
  todayBar: { borderRadius: 2, minHeight: 2, width: 17 },
  todayBarPlanned: { backgroundColor: theme.textSecondary },
  todayBarDone: { backgroundColor: theme.success },
  emptyTrend: { alignItems: 'center', height: 78, justifyContent: 'center', overflow: 'hidden' },
  emptyTrendLine: { backgroundColor: theme.border, height: 1, left: 0, position: 'absolute', right: 0 },
  emptyTrendText: { backgroundColor: theme.cardBackground, color: theme.textSecondary, fontFamily: 'Inter', fontSize: 10, paddingHorizontal: 8, textAlign: 'center' },
  addMeasurementButton: { borderColor: theme.textSecondary, borderRadius: 8, borderWidth: 1, justifyContent: 'center', minHeight: 34, paddingHorizontal: 10 },
  addMeasurementText: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 10 },
});
