import { StyleSheet } from 'react-native';

export const createStyles = (theme) => StyleSheet.create({
  screen: { backgroundColor: theme.background, flex: 1 },
  content: { alignSelf: 'center', gap: 12, maxWidth: 800, paddingBottom: 28, paddingHorizontal: 20, paddingTop: 8, width: '100%' },
  header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  backButton: { alignItems: 'center', height: 40, justifyContent: 'center', width: 40 },
  title: { color: theme.textPrimary, flex: 1, fontFamily: 'Inter-Bold', fontSize: 15, textAlign: 'center' },
  periodRow: { alignItems: 'center', flexDirection: 'row', gap: 7 },
  periodChip: { alignItems: 'center', backgroundColor: theme.cardBackground, borderRadius: 9, justifyContent: 'center', minHeight: 34, paddingHorizontal: 12 },
  periodChipActive: { backgroundColor: theme.primary },
  periodText: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 12 },
  periodTextActive: { color: theme.onPrimary },
  rangeLabel: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 12 },
  metricTabs: { borderBottomColor: theme.border, borderBottomWidth: 1, flexDirection: 'row' },
  metricTab: { alignItems: 'center', flex: 1, justifyContent: 'center', minHeight: 42, paddingHorizontal: 8 },
  metricTabActive: { borderBottomColor: theme.primary, borderBottomWidth: 3 },
  metricTabText: { color: theme.textSecondary, fontFamily: 'Inter-SemiBold', fontSize: 12 },
  metricTabTextActive: { color: theme.primary },
  card: { backgroundColor: theme.cardBackground, borderRadius: 10, gap: 12, padding: 12 },
  cardTitle: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 13 },
  total: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 24 },
  loader: { marginVertical: 55 },
  groupRow: { gap: 5, paddingVertical: 2 },
  groupLabel: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  groupName: { color: theme.textPrimary, flex: 1, fontFamily: 'Inter', fontSize: 11 },
  groupValue: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 10 },
  track: { backgroundColor: theme.textSecondary, borderRadius: 4, height: 7, overflow: 'hidden' },
  fill: { backgroundColor: theme.primary, borderRadius: 4, height: 7 },
  muted: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 11 },
  retry: { color: theme.primary, fontFamily: 'Inter-SemiBold', fontSize: 13, paddingVertical: 10 },
});