import { StyleSheet } from 'react-native';

export const createStyles = (theme) => StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.background },
  content: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 48, gap: 10 },
  title: { color: theme.textPrimary, fontSize: 16, fontFamily: 'Inter-Bold' },
  periodRow: { alignItems: 'center', flexDirection: 'row', gap: 7, paddingRight: 5 },
  periodChip: { alignItems: 'center', backgroundColor: theme.cardBackground, borderRadius: 9, justifyContent: 'center', minHeight: 34, paddingHorizontal: 12 },
  periodChipActive: { backgroundColor: theme.primary },
  periodText: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 12 },
  periodTextActive: { color: theme.onPrimary },
  calendarButton: { alignItems: 'center', height: 40, justifyContent: 'center', width: 36 },
  rangeLabel: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 12 },
  card: { backgroundColor: theme.cardBackground, borderRadius: 10, padding: 12, gap: 7 },
  cardHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  heading: { color: theme.textPrimary, fontSize: 13, fontFamily: 'Inter-SemiBold' },
  cardTitle: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 12 },
  large: { color: theme.textPrimary, fontSize: 24, fontFamily: 'Inter-Bold' },
  muted: { color: theme.textSecondary, fontSize: 13, fontFamily: 'Inter' },
  hint: { color: theme.textPrimary, fontSize: 13, fontFamily: 'Inter', backgroundColor: theme.cardBackground, padding: 12, borderRadius: 10 },
  retry: { alignSelf: 'flex-start', paddingVertical: 10, paddingHorizontal: 14, minHeight: 44, justifyContent: 'center' },
  retryText: { color: theme.primary, fontSize: 14, fontFamily: 'Inter-Bold' },
  record: { borderTopWidth: 1, borderTopColor: theme.border, paddingVertical: 12, minHeight: 56, justifyContent: 'center' },
  recordName: { color: theme.textPrimary, fontSize: 15, fontFamily: 'Inter-SemiBold' },
  metricsGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  metric: { width: '50%', paddingVertical: 8 },
  metricValue: { color: theme.textPrimary, fontSize: 18, fontFamily: 'Inter-Bold' },
  metricDelta: { color: theme.secondary, fontFamily: 'Inter', fontSize: 10 },
  complianceChart: { alignItems: 'flex-end', flexDirection: 'row', gap: 12, height: 82, justifyContent: 'space-around', paddingHorizontal: 4 },
  complianceColumn: { alignItems: 'center', flex: 1, gap: 4, maxWidth: 42 },
  complianceBar: { backgroundColor: theme.textSecondary, borderRadius: 3, justifyContent: 'flex-end', overflow: 'hidden', width: 12 },
  complianceActual: { backgroundColor: theme.success, borderRadius: 3, width: '100%' },
  chartLabel: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 9, textAlign: 'center' },
  intensitySummary: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 70 },
  muscleRow: { alignItems: 'center', flexDirection: 'row', gap: 8, minHeight: 19 },
  muscleName: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 11, width: 52 },
  muscleTrack: { backgroundColor: theme.textSecondary, borderRadius: 4, flex: 1, height: 6, overflow: 'hidden' },
  muscleFill: { backgroundColor: theme.primary, borderRadius: 4, height: 6 },
  muscleCount: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 10, textAlign: 'right', width: 22 },
  modalOverlay: { backgroundColor: theme.overlay, flex: 1, justifyContent: 'flex-end' },
  sheet: { backgroundColor: theme.background, borderTopLeftRadius: 14, borderTopRightRadius: 14, gap: 12, maxHeight: '88%', paddingBottom: 28, paddingHorizontal: 20, paddingTop: 16 },
  sheetHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  sheetTitle: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 13 },
  closeButton: { alignItems: 'center', height: 36, justifyContent: 'center', width: 36 },
  sheetLoader: { marginVertical: 55 },
  intensityStats: { flexDirection: 'row', gap: 10 },
  detailStat: { backgroundColor: theme.cardBackground, borderRadius: 9, flex: 1, gap: 2, minHeight: 92, padding: 10 },
  statLabel: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 11 },
  detailValue: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 23 },
  distributionCard: { backgroundColor: theme.cardBackground, borderRadius: 9, gap: 10, padding: 12 },
  distributionRow: { gap: 4 },
  distributionLabels: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  distributionName: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 11 },
  distributionPercent: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 10 },
  distributionTrack: { backgroundColor: theme.textSecondary, borderRadius: 4, height: 7, overflow: 'hidden' },
  distributionFill: { borderRadius: 4, height: 7 },
  failureRow: { alignItems: 'center', backgroundColor: theme.cardBackground, borderRadius: 9, flexDirection: 'row', justifyContent: 'space-between', minHeight: 52, paddingHorizontal: 12 },
  failureValue: { color: theme.primary, fontFamily: 'Inter-SemiBold', fontSize: 22 },
});
