import { Platform, StyleSheet } from 'react-native';

export const createStyles = (theme) => StyleSheet.create({
  safeArea: { backgroundColor: theme.background, flex: 1 },
  content: { alignSelf: 'center', maxWidth: 800, paddingHorizontal: 20, paddingTop: 10, width: '100%' },
  header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 18 },
  headerTitle: { color: theme.textPrimary, fontSize: 17, fontWeight: '900' },
  backButton: { alignItems: 'center', height: 36, justifyContent: 'center', width: 36 },
  periodRow: { alignItems: 'center', flexDirection: 'row', gap: 7, paddingRight: 6 },
  periodChip: { alignItems: 'center', backgroundColor: theme.cardBackground, borderRadius: 10, minWidth: 45, paddingHorizontal: 9, paddingVertical: 9 },
  periodChipActive: { backgroundColor: theme.primary },
  periodText: { color: theme.textPrimary, fontSize: 12, fontWeight: '800' },
  periodTextActive: { color: theme.onPrimary },
  calendarButton: { alignItems: 'center', height: 38, justifyContent: 'center', marginLeft: 2, width: 32 },
  calendarButtonActive: { borderColor: theme.primary, borderWidth: 1, borderRadius: 9 },
  rangeLabel: { color: theme.textSecondary, fontSize: 13, marginTop: 11 },
  metricTabs: { borderBottomColor: theme.border, borderBottomWidth: 1, marginTop: 13 },
  metricTabsContent: { minWidth: '100%' },
  metricTab: { alignItems: 'center', flexGrow: 1, paddingBottom: 10, paddingHorizontal: 8 },
  metricTabActive: { borderBottomColor: theme.primary, borderBottomWidth: 3 },
  metricTabText: { color: theme.textSecondary, fontSize: 12, fontWeight: '700' },
  metricTabTextActive: { color: theme.primary },
  interactive: { opacity: 0.82 },
  pressed: { opacity: 0.65 },
  loader: { marginTop: 80 },
  card: { backgroundColor: theme.cardBackground, borderRadius: 11, marginTop: 18, padding: 12 },
  cardTitle: { color: theme.textPrimary, fontSize: 14, fontWeight: '800' },
  currentValue: { color: theme.textPrimary, fontSize: 27, fontWeight: '900', marginTop: 3 },
  metaText: { color: theme.textSecondary, fontSize: 13, lineHeight: 21, marginTop: 3 },
  chartBox: { marginTop: 12, overflow: 'hidden', width: '100%' },
  chartLabel: { color: theme.textSecondary, fontSize: 11 },
  chartLabels: { borderTopColor: theme.border, borderTopWidth: 1, height: 26, position: 'relative' },
  chartLabelItem: { position: 'absolute', textAlign: 'center', top: 8 },
  cardEmpty: { paddingBottom: 8, paddingTop: 12 },
  emptyState: { alignItems: 'center', paddingHorizontal: 20, paddingVertical: 70 },
  emptyTitle: { color: theme.textPrimary, fontSize: 15, fontWeight: '800', textAlign: 'center' },
  emptyHint: { color: theme.textSecondary, fontSize: 13, lineHeight: 19, marginTop: 6, textAlign: 'center' },
  retryButton: { borderColor: theme.primary, borderRadius: 10, borderWidth: 1, marginTop: 14, paddingHorizontal: 17, paddingVertical: 10 },
  retryText: { color: theme.primary, fontSize: 13, fontWeight: '800' },
  measurementRow: { alignItems: 'center', borderBottomColor: theme.border, borderBottomWidth: 1, flexDirection: 'row', minHeight: 33 },
  dateText: { color: theme.textSecondary, flex: 1, fontSize: 13 },
  measurementValue: { color: theme.textPrimary, fontSize: 13, textAlign: 'right', width: 95 },
  deltaText: { color: theme.textSecondary, fontSize: 12, textAlign: 'right', width: 75 },
  ctaDock: { backgroundColor: theme.background, bottom: 0, left: 0, paddingBottom: 12, paddingHorizontal: 20, paddingTop: 10, position: 'absolute', right: 0 },
  ctaButton: { alignItems: 'center', alignSelf: 'center', maxWidth: 760, width: '100%', backgroundColor: theme.primary, borderRadius: 12, minHeight: 45, justifyContent: 'center' },
  ctaText: { color: theme.onPrimary, fontSize: 16, fontWeight: '700' },
  overlay: { alignItems: 'center', backgroundColor: theme.overlay, flex: 1, justifyContent: 'center', padding: 18 },
  calendarModal: { backgroundColor: theme.cardBackground, borderRadius: 20, maxWidth: 430, padding: 18, width: '100%' },
  calendarTitle: { color: theme.textPrimary, fontSize: 19, fontWeight: '900', textAlign: 'center' },
  calendarHint: { color: theme.textSecondary, fontSize: 12, lineHeight: 18, marginTop: 5, textAlign: 'center' },
  monthHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  monthArrow: { alignItems: 'center', height: 40, justifyContent: 'center', width: 40 },
  monthTitle: { color: theme.textPrimary, fontSize: 16, fontWeight: '800', textTransform: 'capitalize' },
  weekHeader: { flexDirection: 'row', marginTop: 4 },
  weekLabel: { color: theme.textSecondary, fontSize: 11, fontWeight: '700', textAlign: 'center', width: '14.285%' },
  monthGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 5 },
  monthDay: { alignItems: 'center', height: 43, justifyContent: 'center', position: 'relative', width: '14.285%' },
  rangeFill: { backgroundColor: theme.primary, bottom: 6, left: 0, position: 'absolute', right: 0, top: 6 },
  rangeStart: { borderBottomLeftRadius: 10, borderTopLeftRadius: 10, left: 3 },
  rangeEnd: { borderBottomRightRadius: 10, borderTopRightRadius: 10, right: 3 },
  monthDayText: { color: theme.textPrimary, fontSize: 13, fontWeight: '700', zIndex: 1 },
  outsideMonth: { opacity: 0.25 },
  activeDayText: { color: theme.onPrimary },
  disabled: { opacity: 0.35 },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 16 },
  cancelButton: { alignItems: 'center', borderColor: theme.border, borderRadius: 10, borderWidth: 1, flex: 1, padding: 11 },
  cancelText: { color: theme.textPrimary, fontSize: 13, fontWeight: '800' },
  applyButton: { alignItems: 'center', backgroundColor: theme.primary, borderRadius: 10, flex: 1, padding: 11 },
  applyText: { color: theme.onPrimary, fontSize: 13, fontWeight: '800' },
  input: { ...Platform.select({ web: { outlineStyle: 'none' }, default: {} }) },
});
