import { StyleSheet } from 'react-native';

import { palette } from '../constants/colors';
export const createStyles = (theme) => StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: theme.background },
  mainContainer: { flex: 1, padding: 20 },
  centerContainer: {
    flex: 1,
    backgroundColor: theme.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: { fontSize: 24, fontWeight: 'bold', color: theme.textPrimary, marginBottom: 15 },
  listContainer: { flex: 1 },
  sectionTitle: {
    fontSize: 13,
    color: theme.textSecondary,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 25,
    backgroundColor: palette.orangeLegacy,
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    boxShadow: palette.webShadowSmall,
  },
  fabIcon: { color: palette.whitePure, fontSize: 32, fontWeight: '300', marginTop: -3 },
  toastContainer: {
    position: 'absolute',
    bottom: 30,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    boxShadow: palette.webShadowMedium,
    elevation: 6,
    zIndex: 2000,
    maxWidth: '90%',
  },
  toastSuccess: { backgroundColor: palette.success },
  toastError: { backgroundColor: palette.red },
  toastText: { color: palette.whitePure, fontSize: 14, fontWeight: '600', flex: 1, marginRight: 12 },
  toastClose: { padding: 4 },
  toastCloseText: { color: palette.whitePure, fontSize: 14, fontWeight: 'bold' },
});
