import { StyleSheet } from 'react-native';
import { palette } from '../constants/colors';

export const createStyles = (theme) => StyleSheet.create({
  safeArea: { backgroundColor: theme.background, flex: 1 },
  topBar: { alignItems: 'center', borderBottomColor: theme.border, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 10 },
  backButton: { alignItems: 'center', height: 40, justifyContent: 'center', width: 40 },
  topBarTitle: { color: theme.textPrimary, fontSize: 16, fontWeight: '900' },
  loader: { marginTop: 80 },
  errorState: { alignItems: 'center', gap: 14, padding: 40 },
  errorText: { color: theme.textPrimary, fontSize: 16, fontWeight: '800', textAlign: 'center' },
  retryButton: { borderColor: theme.primary, borderRadius: 10, borderWidth: 1, paddingHorizontal: 16, paddingVertical: 10 },
  retryText: { color: theme.primary, fontWeight: '900' },
  content: { alignSelf: 'center', gap: 14, maxWidth: 800, padding: 18, width: '100%' },
  hero: { gap: 5 },
  completedLabel: { color: theme.success, fontSize: 11, fontWeight: '900', letterSpacing: 1.3 },
  title: { color: theme.textPrimary, fontSize: 27, fontWeight: '900' },
  date: { color: theme.textSecondary, fontSize: 13, lineHeight: 19, textTransform: 'capitalize' },
  summaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  summaryTile: { backgroundColor: theme.cardBackground, borderColor: theme.border, borderRadius: 14, borderWidth: 1, flexBasis: '47%', flexGrow: 1, gap: 4, minHeight: 100, padding: 13 },
  summaryValue: { color: theme.textPrimary, fontSize: 19, fontWeight: '900', marginTop: 2 },
  summaryLabel: { color: theme.textSecondary, fontSize: 11, fontWeight: '700' },
  statsCard: { backgroundColor: theme.cardBackground, borderColor: theme.border, borderRadius: 16, borderWidth: 1, paddingHorizontal: 15 },
  statRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 13 },
  statLabel: { color: theme.textSecondary, fontSize: 13, fontWeight: '700' },
  statValue: { color: theme.textPrimary, fontSize: 14, fontWeight: '900' },
  divider: { backgroundColor: theme.border, height: StyleSheet.hairlineWidth },
  sourceCard: { backgroundColor: theme.cardBackground, borderColor: theme.border, borderRadius: 16, borderWidth: 1, paddingHorizontal: 15 },
  sourceRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 14 },
  sourceDivider: { borderTopColor: theme.border, borderTopWidth: StyleSheet.hairlineWidth },
  sourceText: { flex: 1, gap: 3 },
  sourceLabel: { color: theme.textSecondary, fontSize: 11, fontWeight: '800', textTransform: 'uppercase' },
  sourceValue: { color: theme.textPrimary, fontSize: 14, fontWeight: '800' },
  sourceLink: { color: theme.primary },
  unavailable: { color: theme.textSecondary, fontSize: 11 },
  scheduleNote: { color: theme.secondary, fontSize: 11, fontWeight: '700' },
  notice: { alignItems: 'flex-start', backgroundColor: theme.filterChipBackground, borderRadius: 12, flexDirection: 'row', gap: 9, padding: 12 },
  noticeText: { color: theme.textSecondary, flex: 1, fontSize: 12, lineHeight: 18 },
  sectionTitle: { color: theme.textPrimary, fontSize: 20, fontWeight: '900', marginTop: 6 },
  exerciseCard: { backgroundColor: theme.cardBackground, borderColor: theme.border, borderRadius: 16, borderWidth: 1, overflow: 'hidden' },
  exerciseHeader: { alignItems: 'center', flexDirection: 'row', gap: 9, padding: 15 },
  exerciseHeading: { flex: 1, gap: 5 },
  exerciseName: { color: theme.textPrimary, fontSize: 16, fontWeight: '900' },
  badges: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  addedBadge: { backgroundColor: theme.filterChipBackground, borderRadius: 999, color: theme.secondary, fontSize: 10, fontWeight: '800', overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 4 },
  missedBadge: { backgroundColor: palette.redWash, borderRadius: 999, color: theme.error, fontSize: 10, fontWeight: '800', overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 4 },
  exerciseProgress: { color: theme.textSecondary, fontSize: 12, fontWeight: '700' },
  exerciseBody: { borderTopColor: theme.border, borderTopWidth: 1, gap: 13, padding: 15 },
  planRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  planLabel: { color: theme.textSecondary, fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  planValue: { color: theme.textPrimary, fontSize: 13, fontWeight: '800' },
  noPlan: { color: theme.textSecondary, fontSize: 12, fontStyle: 'italic' },
  table: { borderColor: theme.border, borderRadius: 10, borderWidth: 1, overflow: 'hidden' },
  tableHeader: { backgroundColor: theme.filterChipBackground },
  tableRow: { alignItems: 'center', borderBottomColor: theme.border, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', minHeight: 38 },
  tableCell: { color: theme.textSecondary, flex: 1, fontSize: 9, fontWeight: '900', textAlign: 'center', textTransform: 'uppercase' },
  tableCellText: { color: theme.textPrimary, flex: 1, fontSize: 12, fontWeight: '700', textAlign: 'center' },
  setCell: { flex: 0.7 },
  failureValue: { color: theme.error, fontWeight: '900' },
  noActualSets: { color: theme.textSecondary, fontSize: 13, fontStyle: 'italic', paddingVertical: 8 },
  notesCard: { backgroundColor: theme.cardBackground, borderColor: theme.border, borderRadius: 16, borderWidth: 1, gap: 7, padding: 15 },
  notesTitle: { color: theme.textSecondary, fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  notesText: { color: theme.textPrimary, fontSize: 14, lineHeight: 21 },
});
