import { Platform, StyleSheet } from 'react-native';
import { palette } from '../constants/colors';

export const createStyles = (theme) => StyleSheet.create({
  safeArea: { backgroundColor: theme.background, flex: 1 },
  listContent: { alignSelf: 'center', maxWidth: 800, paddingHorizontal: 18, width: '100%' },
  emptyList: { flexGrow: 1 },
  headerContent: { gap: 16, paddingBottom: 18, paddingTop: 10 },
  headingRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  eyebrow: { color: theme.primary, fontSize: 11, fontWeight: '900', letterSpacing: 1.4 },
  heading: { color: theme.textPrimary, fontSize: 29, fontWeight: '900', marginTop: 3 },
  calendarButton: { alignItems: 'center', borderColor: theme.border, borderRadius: 13, borderWidth: 1, height: 46, justifyContent: 'center', width: 46 },
  searchBox: { alignItems: 'center', backgroundColor: theme.inputBackground, borderRadius: 13, flexDirection: 'row', gap: 9, minHeight: 48, paddingHorizontal: 14 },
  searchInput: { color: theme.inputText, flex: 1, fontSize: 14, outlineStyle: Platform.OS === 'web' ? 'none' : undefined, paddingVertical: 12 },
  filters: { gap: 8, paddingRight: 18 },
  filterChip: { backgroundColor: theme.filterChipBackground, borderRadius: 999, paddingHorizontal: 15, paddingVertical: 9 },
  filterChipActive: { backgroundColor: theme.filterChipActiveBackground },
  filterText: { color: theme.filterChipText, fontSize: 12, fontWeight: '800' },
  filterTextActive: { color: theme.filterChipActiveText },
  appliedRange: { alignItems: 'center', alignSelf: 'flex-start', borderColor: theme.primary, borderRadius: 10, borderWidth: 1, flexDirection: 'row', gap: 7, paddingHorizontal: 11, paddingVertical: 8 },
  appliedRangeText: { color: theme.textPrimary, fontSize: 12, fontWeight: '800' },
  loader: { marginTop: 70 },
  empty: { alignItems: 'center', alignSelf: 'center', gap: 9, justifyContent: 'center', maxWidth: 340, paddingHorizontal: 24, paddingVertical: 64 },
  emptyTitle: { color: theme.textPrimary, fontSize: 19, fontWeight: '900', textAlign: 'center' },
  emptyHint: { color: theme.textSecondary, fontSize: 13, lineHeight: 19, textAlign: 'center' },
  emptyAction: { borderColor: theme.primary, borderRadius: 10, borderWidth: 1, marginTop: 7, paddingHorizontal: 15, paddingVertical: 10 },
  emptyActionText: { color: theme.primary, fontSize: 13, fontWeight: '900' },
  footerLoader: { padding: 20 },
  retryPage: { alignItems: 'center', padding: 18 },
  retryPageText: { color: theme.primary, fontSize: 13, fontWeight: '800' },
  overlay: { alignItems: 'center', backgroundColor: palette.overlay72, flex: 1, justifyContent: 'center', padding: 18 },
  calendarModal: { backgroundColor: theme.cardBackground, borderColor: theme.border, borderRadius: 22, borderWidth: 1, maxWidth: 420, padding: 18, width: '100%' },
  calendarTitle: { color: theme.textPrimary, fontSize: 20, fontWeight: '900', textAlign: 'center' },
  calendarHint: { color: theme.textSecondary, fontSize: 12, lineHeight: 18, marginTop: 5, textAlign: 'center' },
  monthHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  monthArrow: { alignItems: 'center', height: 42, justifyContent: 'center', width: 42 },
  monthTitle: { color: theme.textPrimary, fontSize: 16, fontWeight: '900', textTransform: 'capitalize' },
  weekHeader: { flexDirection: 'row', marginTop: 4 },
  weekLabel: { color: theme.textSecondary, fontSize: 11, fontWeight: '700', textAlign: 'center', width: '14.285%' },
  monthGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 5 },
  monthDay: { alignItems: 'center', height: 45, justifyContent: 'center', position: 'relative', width: '14.285%' },
  rangeFill: { backgroundColor: theme.primary, bottom: 7, left: 0, position: 'absolute', right: 0, top: 7 },
  rangeStart: { borderBottomLeftRadius: 11, borderTopLeftRadius: 11, left: 3 },
  rangeEnd: { borderBottomRightRadius: 11, borderTopRightRadius: 11, right: 3 },
  monthDayText: { color: theme.textPrimary, fontSize: 13, fontWeight: '800', zIndex: 1 },
  outsideMonth: { color: theme.textSecondary, opacity: 0.25 },
  activeDayText: { color: palette.whitePure },
  disabled: { opacity: 0.35 },
  workoutDot: { backgroundColor: theme.secondary, borderRadius: 3, height: 5, marginTop: 3, width: 5, zIndex: 1 },
  activeDot: { backgroundColor: palette.whitePure },
  legend: { alignItems: 'center', flexDirection: 'row', gap: 7, marginTop: 8 },
  legendText: { color: theme.textSecondary, fontSize: 11 },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 18 },
  cancelButton: { alignItems: 'center', borderColor: theme.border, borderRadius: 11, borderWidth: 1, flex: 1, padding: 12 },
  cancelText: { color: theme.textPrimary, fontSize: 13, fontWeight: '900' },
  applyButton: { alignItems: 'center', backgroundColor: theme.primary, borderRadius: 11, flex: 1, padding: 12 },
  applyText: { color: palette.whitePure, fontSize: 13, fontWeight: '900' },
});
