import { StyleSheet } from 'react-native';

export const createStyles = (theme) => StyleSheet.create({
  screen: { backgroundColor: theme.background, flex: 1 },
  heading: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 16, lineHeight: 23, marginBottom: 20 },
  muted: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 13, lineHeight: 19 },
  row: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginVertical: 12 },
  chip: { backgroundColor: theme.cardBackground, borderRadius: 14, justifyContent: 'center', minHeight: 30, paddingHorizontal: 10, paddingVertical: 6 },
  selected: { backgroundColor: theme.primary },
  segmentLabel: { color: theme.textSecondary, fontSize: 16 },
  segmentLabelActive: { color: theme.onPrimary },
  separator: { height: 8 },
  empty: { padding: 24 },
  content: {
    paddingHorizontal: 20,
    paddingTop: 28,
    paddingBottom: 28,
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
  },
  segment: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.border,
    flexDirection: "row",
    marginHorizontal: 12,
    overflow: "hidden",
  },
  segmentItem: {
    flex: 1,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  },
  search: {
    marginTop: 22,
    marginBottom: 28,
    height: 50,
    borderColor: theme.primary,
    borderRadius: 12,
    backgroundColor: theme.inputBackground,
  },
  searchInput: { color: theme.inputText, fontSize: 16 },
  sort: {
    flexDirection: "row",
    alignItems: "center",
    width: 237,
    minHeight: 30,
    backgroundColor: theme.cardBackground,
    borderColor: theme.border,
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 8,
    marginBottom: 12,
  },
});
