import { StyleSheet } from 'react-native';
import { palette } from '../constants/colors';

export const createStyles = (theme) => StyleSheet.create({
  screen: { backgroundColor: theme.background, flex: 1 },
  heading: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 16, lineHeight: 23, marginBottom: 20 },
  muted: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 13, lineHeight: 19 },
  selected: { backgroundColor: theme.primary },
  segmentLabel: { color: theme.textSecondary, fontSize: 16 },
  segmentLabelActive: { color: palette.black },
  separator: { height: 8 },
  empty: { padding: 24 },
  content: {
    paddingHorizontal: 20,
    paddingTop: 28,
    paddingBottom: 28,
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
  },
  segment: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.border,
    flexDirection: "row",
    overflow: "hidden",
    width: '100%',
  },
  segmentItem: {
    flex: 1,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  },
  searchRow: { alignItems: 'center', flexDirection: 'row', gap: 8, marginTop: 16 },
  search: {
    flex: 1,
    height: 40,
    borderRadius: 12,
    backgroundColor: theme.inputBackground,
  },
  searchInput: { color: theme.inputText, fontSize: 16 },
  filterButton: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  filtersLabel: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 13, lineHeight: 18, marginTop: 16 },
  scopeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  scopeChip: { borderColor: theme.border, borderRadius: 12, borderWidth: 1, minHeight: 32, paddingHorizontal: 12, paddingVertical: 6 },
  scopeChipSelected: { backgroundColor: theme.primary, borderColor: theme.primary },
  scopeLabel: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 13 },
  scopeLabelSelected: { color: palette.black },
  createProgram: {
    alignItems: 'center',
    borderColor: theme.border,
    borderRadius: 8,
    borderStyle: 'dashed',
    borderWidth: 1,
    justifyContent: 'center',
    marginBottom: 12,
    minHeight: 56,
    paddingHorizontal: 16,
  },
  createProgramText: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 16 },
});
