import { StyleSheet } from 'react-native';

export const createStyles = (theme) => StyleSheet.create({
  spinner: { margin: 24 },
  screen: { flex: 1, backgroundColor: theme.background },
  content: {
    padding: 20,
    paddingBottom: 28,
    gap: 16,
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
  },
  title: { color: theme.textPrimary, fontSize: 24, fontFamily: "Inter-SemiBold", lineHeight: 34 },
  heading: {
    color: theme.textPrimary,
    fontSize: 16,
    fontFamily: "Inter-Bold",
    lineHeight: 23,
  },
  text: { color: theme.textPrimary, fontFamily: "Inter", fontSize: 14, lineHeight: 20 },
  muted: { color: theme.textSecondary, fontFamily: "Inter", fontSize: 13, lineHeight: 19 },
  error: { color: theme.error, fontSize: 13 },
  link: { color: theme.primary, fontSize: 13, fontFamily: "Inter-SemiBold" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
  },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  button: {
    minHeight: 44,
    borderRadius: 14,
    backgroundColor: theme.primary,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    fontFamily: "Inter-SemiBold",
    color: theme.onPrimary,
    fontSize: 13,
    textAlign: "center",
  },
  secondary: {
    backgroundColor: theme.cardBackground,
    borderWidth: 1,
    borderColor: theme.border,
  },
  input: {
    fontFamily: "Inter",
    minHeight: 44,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.cardBackground,
    borderRadius: 10,
    padding: 12,
    color: theme.textPrimary,
    fontSize: 14,
  },
  row: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 8 },
  chip: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: theme.cardBackground,
    borderRadius: 14,
    minHeight: 30,
    justifyContent: "center",
  },
  selected: { backgroundColor: theme.primary },
  overlay: {
    flex: 1,
    backgroundColor: theme.overlay,
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
  },
  sheet: {
    backgroundColor: theme.background,
    borderColor: theme.border,
    borderWidth: 1,
    borderRadius: 18,
    padding: 16,
    width: "100%",
    maxWidth: 700,
    maxHeight: "95%",
  },
  sheetBody: { gap: 16, paddingTop: 16, paddingBottom: 16 },
  feedback: { gap: 12, paddingVertical: 12 },
  media: {
    aspectRatio: 333 / 226,
    alignSelf: "center",
    borderRadius: 8,
    backgroundColor: theme.cardBackground,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginHorizontal: 10,
    maxWidth: 520,
    width: "94%",
  },
});
