import { StyleSheet } from 'react-native';

import { palette } from '../../constants/colors';
export const s = StyleSheet.create({
  spinner: { margin: 24 },
  screen: { flex: 1, backgroundColor: palette.black },
  content: {
    padding: 20,
    paddingBottom: 28,
    gap: 16,
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
  },
  title: { color: palette.white, fontSize: 24, fontFamily: "Inter-SemiBold", lineHeight: 34 },
  heading: {
    color: palette.white,
    fontSize: 16,
    fontFamily: "Inter-Bold",
    lineHeight: 23,
  },
  text: { color: palette.white, fontFamily: "Inter", fontSize: 14, lineHeight: 20 },
  muted: { color: palette.lightGray, fontFamily: "Inter", fontSize: 13, lineHeight: 19 },
  error: { color: palette.errorSoft, fontSize: 13 },
  link: { color: palette.accent, fontSize: 13, fontFamily: "Inter-SemiBold" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
  },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  button: {
    minHeight: 44,
    borderRadius: 14,
    backgroundColor: palette.accent,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    fontFamily: "Inter-SemiBold",
    color: palette.white,
    fontSize: 13,
    textAlign: "center",
  },
  secondary: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.borderDark,
  },
  input: {
    fontFamily: "Inter",
    minHeight: 44,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    backgroundColor: palette.surfaceDark,
    borderRadius: 10,
    padding: 12,
    color: palette.white,
    fontSize: 14,
  },
  row: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 8 },
  chip: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: palette.surface,
    borderRadius: 14,
    minHeight: 30,
    justifyContent: "center",
  },
  selected: { backgroundColor: palette.accent },
  overlay: {
    flex: 1,
    backgroundColor: palette.blackTranslucent,
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
  },
  sheet: {
    backgroundColor: palette.black,
    borderColor: palette.borderDark,
    borderWidth: 1,
    borderRadius: 18,
    padding: 16,
    width: "100%",
    maxWidth: 700,
    maxHeight: "95%",
  },
  sheetBody: { gap: 16, paddingTop: 16, paddingBottom: 16 },
  feedback: { gap: 12, paddingVertical: 12 },
  media: {
    height: 226,
    borderRadius: 8,
    backgroundColor: palette.surfacePlaceholder,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginHorizontal: 10,
  },
});
