import { StyleSheet } from 'react-native';

import { palette } from '../../constants/colors';

export const createStyles = (theme) => StyleSheet.create({
  page: { gap: 24 },
  hero: {
    alignItems: 'center',
    backgroundColor: palette.slate950,
    borderColor: palette.slate700,
    borderRadius: 24,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
    overflow: 'hidden',
    padding: 24,
  },
  heroCopy: { flex: 1, gap: 7, minWidth: 230 },
  eyebrow: { alignItems: 'center', flexDirection: 'row', gap: 7 },
  eyebrowText: { color: palette.greenBorder, fontSize: 11, fontWeight: '800', letterSpacing: 1.2 },
  heroTitle: { color: palette.slate50, fontSize: 30, fontWeight: '800' },
  heroText: { color: palette.slate300, fontSize: 14, lineHeight: 21, maxWidth: 640 },
  updated: { color: palette.slate400, fontSize: 12 },
  score: {
    alignItems: 'center',
    borderColor: palette.greenBright,
    borderRadius: 54,
    borderWidth: 5,
    height: 108,
    justifyContent: 'center',
    width: 108,
  },
  scoreValue: { color: palette.whitePure, fontSize: 32, fontWeight: '900' },
  scoreTotal: { color: palette.slate400, fontSize: 13, fontWeight: '700' },
  scoreLabel: { color: palette.greenBorder, fontSize: 10, fontWeight: '800', textTransform: 'uppercase' },
  refreshButton: { minWidth: 110 },
  sectionHeader: { alignItems: 'center', flexDirection: 'row', gap: 11 },
  sectionIcon: {
    alignItems: 'center',
    backgroundColor: palette.accentTint,
    borderRadius: 10,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  healthGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  healthCard: {
    alignItems: 'center',
    backgroundColor: theme.cardBackground,
    borderColor: theme.border,
    borderRadius: 14,
    borderWidth: 1,
    flexBasis: 190,
    flexDirection: 'row',
    flexGrow: 1,
    gap: 11,
    minHeight: 74,
    padding: 14,
  },
  statusGlow: { alignItems: 'center', borderRadius: 18, height: 36, justifyContent: 'center', width: 36 },
  statusDot: { borderRadius: 5, height: 10, width: 10 },
  healthCopy: { flex: 1, gap: 3 },
  healthName: { color: theme.textPrimary, fontSize: 14, fontWeight: '700' },
  healthStatus: { fontSize: 11, fontWeight: '800', textTransform: 'uppercase' },
  metricSection: { gap: 13 },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  metricCard: {
    backgroundColor: theme.cardBackground,
    borderColor: theme.border,
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: 175,
    flexGrow: 1,
    gap: 7,
    minHeight: 116,
    overflow: 'hidden',
    padding: 17,
  },
  metricLine: { backgroundColor: theme.primary, borderRadius: 2, height: 3, width: 42 },
  metricValue: { color: theme.textPrimary, fontSize: 27, fontWeight: '900', letterSpacing: -0.5 },
  metricLabel: { color: theme.textSecondary, fontSize: 12, lineHeight: 17 },
  twoColumn: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
  panel: {
    backgroundColor: theme.cardBackground,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    flexBasis: 330,
    flexGrow: 1,
    gap: 15,
    padding: 18,
  },
  logRow: { alignItems: 'center', borderTopColor: theme.border, borderTopWidth: 1, flexDirection: 'row', gap: 12, justifyContent: 'space-between', paddingTop: 12 },
  logService: { color: theme.textPrimary, fontSize: 14, fontWeight: '700' },
  logCounts: { flexDirection: 'row', gap: 10 },
  warningCount: { color: palette.amber, fontSize: 12, fontWeight: '800' },
  errorCount: { color: palette.redSoft, fontSize: 12, fontWeight: '800' },
  traceList: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  traceChip: { alignItems: 'center', backgroundColor: palette.skyTint, borderColor: palette.sky, borderRadius: 20, borderWidth: 1, flexDirection: 'row', gap: 7, paddingHorizontal: 12, paddingVertical: 8 },
  traceText: { color: theme.textPrimary, fontSize: 12, fontWeight: '700' },
  securityNote: { alignItems: 'center', backgroundColor: palette.successPale, borderColor: palette.greenBorder, borderRadius: 14, borderWidth: 1, flexDirection: 'row', gap: 12, padding: 16 },
  securityText: { color: palette.greenDarkText, flex: 1, fontSize: 12, lineHeight: 18 },
});
