import { StyleSheet } from 'react-native';
import { palette } from '../../constants/colors';

export const createStyles = (theme) => StyleSheet.create({
  container: { alignSelf: 'center', gap: 16, maxWidth: 1040, width: '100%' },
  headingRow: { alignItems: 'flex-start', flexDirection: 'row', flexWrap: 'wrap', gap: 14, justifyContent: 'space-between' },
  headingCopy: { flex: 1, gap: 3, minWidth: 220 },
  compactHint: { color: theme.textSecondary, flex: 1, fontFamily: 'Inter', fontSize: 11, lineHeight: 16 },
  historyButton: { alignItems: 'center', backgroundColor: theme.cardBackground, borderColor: theme.border, borderRadius: 12, borderWidth: 1, flexDirection: 'row', gap: 7, minHeight: 42, paddingHorizontal: 13 },
  historyButtonText: { color: theme.primary, fontFamily: 'Inter-SemiBold', fontSize: 12 },
  formColumns: { gap: 14 },
  formColumnsDesktop: { alignItems: 'flex-start', flexDirection: 'row' },
  column: { flex: 1, gap: 14, minWidth: 0 },
  sectionCard: { backgroundColor: theme.cardBackground, borderColor: theme.border, borderRadius: 15, borderWidth: 1, gap: 13, padding: 15 },
  sectionTitle: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 14 },
  fieldLabel: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 13 },
  choiceRow: { flexDirection: 'row', gap: 8 },
  choice: { alignItems: 'center', borderColor: theme.border, borderRadius: 10, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 42, paddingHorizontal: 11 },
  choiceActive: { backgroundColor: theme.primary, borderColor: theme.primary },
  choiceText: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 12 },
  choiceTextActive: { color: theme.onPrimary },
  categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  categoryChip: { alignItems: 'center', backgroundColor: theme.filterChipBackground, borderColor: theme.border, borderRadius: 11, borderWidth: 1, flexDirection: 'row', gap: 7, minHeight: 42, paddingHorizontal: 12 },
  categoryChipActive: { backgroundColor: theme.primary, borderColor: theme.primary },
  categoryIndicator: { borderColor: theme.textSecondary, borderRadius: 6, borderWidth: 1, height: 11, width: 11 },
  categoryIndicatorActive: { backgroundColor: theme.onPrimary, borderColor: theme.onPrimary },
  categoryText: { color: theme.filterChipText, fontFamily: 'Inter-SemiBold', fontSize: 12 },
  categoryTextActive: { color: theme.onPrimary },
  inlineFields: { alignItems: 'flex-end', flexDirection: 'row', gap: 8 },
  growField: { flex: 1, minWidth: 0 },
  addButton: { minWidth: 72 },
  selectedMediaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  selectedMediaCard: { borderRadius: 10, overflow: 'hidden', position: 'relative', width: 104 },
  selectedMediaImage: { aspectRatio: 16 / 10, backgroundColor: theme.mediaPlaceholder, width: '100%' },
  removeMedia: { alignItems: 'center', backgroundColor: palette.overlay70, borderRadius: 12, height: 24, justifyContent: 'center', position: 'absolute', right: 5, top: 5, width: 24 },
  videoList: { gap: 7 },
  videoPill: { alignItems: 'center', backgroundColor: theme.filterChipBackground, borderRadius: 10, flexDirection: 'row', gap: 7, minHeight: 38, paddingHorizontal: 10 },
  videoPillText: { color: theme.textPrimary, flex: 1, fontFamily: 'Inter', fontSize: 11 },
  inlineHint: { alignItems: 'flex-start', flexDirection: 'row', gap: 6 },
  success: { color: theme.success, fontFamily: 'Inter-SemiBold', fontSize: 13 },
  sendBar: { alignItems: 'flex-end', borderTopColor: theme.border, borderTopWidth: 1, paddingTop: 14 },
  sendButton: { minWidth: 220 },
  segmented: { alignSelf: 'flex-start', backgroundColor: theme.filterChipBackground, borderRadius: 12, flexDirection: 'row', padding: 3 },
  segment: { borderRadius: 9, justifyContent: 'center', minHeight: 38, paddingHorizontal: 14 },
  segmentActive: { backgroundColor: theme.primary },
  segmentText: { color: theme.filterChipText, fontFamily: 'Inter-SemiBold', fontSize: 12 },
  segmentTextActive: { color: theme.onPrimary },
  historyFilters: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  filterChip: { alignItems: 'center', backgroundColor: theme.filterChipBackground, borderRadius: 10, justifyContent: 'center', minHeight: 38, paddingHorizontal: 11 },
  filterChipActive: { backgroundColor: theme.filterChipActiveBackground },
  filterText: { color: theme.filterChipText, fontFamily: 'Inter-SemiBold', fontSize: 11 },
  filterTextActive: { color: theme.filterChipActiveText },
  calendarButton: { alignItems: 'center', backgroundColor: theme.filterChipBackground, borderRadius: 10, height: 38, justifyContent: 'center', width: 40 },
  selectedDate: { alignItems: 'center', alignSelf: 'flex-start', borderColor: theme.primary, borderRadius: 10, borderWidth: 1, flexDirection: 'row', gap: 7, minHeight: 38, paddingHorizontal: 11 },
  selectedDateText: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 11 },
  dayGroup: { gap: 9 },
  dayHeading: { color: theme.textSecondary, fontFamily: 'Inter-Bold', fontSize: 11, textTransform: 'uppercase' },
  historyCard: { backgroundColor: theme.cardBackground, borderColor: theme.border, borderRadius: 14, borderWidth: 1, gap: 8, padding: 14 },
  historyCardHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  categoryLabel: { color: theme.primary, fontFamily: 'Inter-Bold', fontSize: 10, textTransform: 'uppercase' },
  timeText: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 10 },
  cardTitle: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 15 },
  cardBody: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 13, lineHeight: 19 },
  counts: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 10 },
  mediaStrip: { gap: 8 },
  historyMedia: { borderRadius: 9, height: 92, width: 148 },
  videoCard: { backgroundColor: theme.filterChipBackground, borderRadius: 9, overflow: 'hidden', width: 180 },
  videoThumb: { height: 92, width: '100%' },
  videoLabel: { alignItems: 'center', flexDirection: 'row', gap: 5, padding: 8 },
  videoText: { color: theme.textPrimary, flex: 1, fontFamily: 'Inter', fontSize: 10 },
  linkPreview: { alignItems: 'center', flexDirection: 'row', gap: 6 },
  linkPreviewText: { color: theme.primary, flex: 1, fontFamily: 'Inter', fontSize: 11 },
  imageHistoryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  imageHistoryCard: { backgroundColor: theme.cardBackground, borderColor: theme.border, borderRadius: 11, borderWidth: 1, gap: 6, overflow: 'hidden', paddingBottom: 7, width: 150 },
  imageHistoryImage: { aspectRatio: 16 / 10, backgroundColor: theme.mediaPlaceholder, width: '100%' },
  imageMeta: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 10, paddingHorizontal: 8 },
  emptyState: { alignItems: 'center', gap: 9, paddingVertical: 48 },
  emptyText: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 13, textAlign: 'center' },
  pressed: { opacity: 0.72 },
  overlay: { alignItems: 'center', backgroundColor: palette.overlay72, flex: 1, justifyContent: 'center', padding: 18 },
  calendarModal: { backgroundColor: theme.cardBackground, borderColor: theme.border, borderRadius: 22, borderWidth: 1, maxWidth: 420, padding: 18, width: '100%' },
  calendarTitle: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 19, textAlign: 'center' },
  monthHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  monthArrow: { alignItems: 'center', height: 42, justifyContent: 'center', width: 42 },
  monthTitle: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 15, textTransform: 'capitalize' },
  weekHeader: { flexDirection: 'row', marginTop: 4 },
  weekLabel: { color: theme.textSecondary, fontFamily: 'Inter-SemiBold', fontSize: 10, textAlign: 'center', width: '14.285%' },
  monthGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 5 },
  monthDay: { alignItems: 'center', height: 45, justifyContent: 'center', width: '14.285%' },
  dayCircle: { alignItems: 'center', borderRadius: 12, height: 30, justifyContent: 'center', width: 30 },
  dayCircleActive: { backgroundColor: theme.primary },
  monthDayText: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 12 },
  activeDayText: { color: theme.onPrimary },
  historyDot: { backgroundColor: theme.secondary, borderRadius: 3, height: 5, marginTop: 2, width: 5 },
  activeDot: { backgroundColor: theme.onPrimary },
  disabled: { opacity: 0.35 },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 18 },
  cancelButton: { alignItems: 'center', borderColor: theme.border, borderRadius: 11, borderWidth: 1, flex: 1, padding: 12 },
  cancelText: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 13 },
  applyButton: { alignItems: 'center', backgroundColor: theme.primary, borderRadius: 11, flex: 1, padding: 12 },
  applyText: { color: theme.onPrimary, fontFamily: 'Inter-Bold', fontSize: 13 },
});
