import { StyleSheet } from 'react-native';

import { palette } from '../../constants/colors';

export const createStyles = (theme) => StyleSheet.create({
  root: { gap: 24 },
  topBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  hero: {
    backgroundColor: theme.cardBackground,
    borderColor: theme.border,
    borderWidth: 1,
    borderRadius: 18,
    padding: 22,
    gap: 18,
  },
  identity: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 16 },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.accentTint,
    overflow: 'hidden',
  },
  avatarImage: { width: '100%', height: '100%' },
  avatarPressed: { opacity: 0.72 },
  avatarText: { color: palette.redSoft, fontSize: 24, fontWeight: '800' },
  identityText: { flex: 1, minWidth: 220, gap: 4 },
  name: { color: theme.textPrimary, fontSize: 25, fontWeight: '700' },
  roleRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8 },
  roleBadge: {
    borderColor: theme.border,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  status: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  dot: { width: 7, height: 7, borderRadius: 4 },
  section: { gap: 14 },
  sectionTitle: { color: theme.textPrimary, fontSize: 19, fontWeight: '700' },
  infoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  infoItem: {
    flexBasis: 220,
    flexGrow: 1,
    backgroundColor: theme.cardBackground,
    borderColor: theme.border,
    borderWidth: 1,
    borderRadius: 14,
    padding: 15,
    gap: 5,
  },
  infoLabel: { color: theme.textSecondary, fontSize: 12 },
  infoValue: { color: theme.textPrimary, fontSize: 15, fontWeight: '600' },
  statItem: {
    flexBasis: 180,
    flexGrow: 1,
    backgroundColor: theme.cardBackground,
    borderRadius: 14,
    padding: 16,
    gap: 6,
  },
  statValue: { color: theme.textPrimary, fontSize: 24, fontWeight: '800' },
  divider: { height: 1, backgroundColor: theme.border },
  filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  filter: {
    minHeight: 36,
    borderColor: theme.border,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 13,
    justifyContent: 'center',
  },
  filterActive: { backgroundColor: theme.primary, borderColor: theme.primary },
  filterText: { color: theme.textSecondary, fontSize: 13, fontWeight: '600' },
  filterTextActive: { color: theme.onPrimary },
  timeline: { gap: 0 },
  activity: {
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 15,
    borderBottomColor: theme.border,
    borderBottomWidth: 1,
  },
  activityMarker: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: theme.primary,
    marginTop: 5,
  },
  activityBody: { flex: 1, gap: 4 },
  activityTitle: { color: theme.textPrimary, fontSize: 14, fontWeight: '600' },
  activityMeta: { color: theme.textSecondary, fontSize: 12, lineHeight: 18 },
  empty: { color: theme.textSecondary, textAlign: 'center', paddingVertical: 28 },
  avatarBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.88)',
    padding: 24,
  },
  avatarPreview: {
    width: '100%',
    maxWidth: 720,
    alignItems: 'center',
    gap: 18,
  },
  avatarPreviewImage: {
    width: '100%',
    maxHeight: 720,
    aspectRatio: 1,
    borderRadius: 22,
  },
});
