import { StyleSheet } from 'react-native';
import { palette } from '../../constants/colors';

export const createStyles = (theme, compact = false) => StyleSheet.create({
  addSet: { backgroundColor: theme.surfaceElevated, borderRadius: 8, justifyContent: 'center', minHeight: 44, paddingHorizontal: 12 },
  addSetText: { color: theme.secondary, fontFamily: 'Inter-SemiBold', fontSize: 13 },
  card: { backgroundColor: theme.cardBackground, borderRadius: 9, borderWidth: 1, overflow: 'hidden' },
  cardBody: { gap: 10, padding: 10, paddingTop: 0 },
  cardHeader: { alignItems: 'center', flexDirection: 'row', gap: 8, minHeight: 54, paddingHorizontal: 10 },
  cardTitleBlock: { flex: 1 },
  completeText: { color: palette.greenBright },
  completedCard: { backgroundColor: theme.background === palette.black ? palette.greenDark : palette.successPale },
  confirmCheck: { alignItems: 'center', borderColor: theme.border, borderRadius: 20, borderWidth: 1, height: 38, justifyContent: 'center', width: 38 },
  confirmDisabled: { opacity: 0.45 },
  confirmed: { backgroundColor: palette.greenBright, borderColor: palette.greenBright },
  detailsButton: { alignSelf: 'flex-start', minHeight: 32, justifyContent: 'center' },
  detailsText: { color: theme.primary, fontFamily: 'Inter-SemiBold', fontSize: 12 },
  disabled: { opacity: 0.45 },
  exerciseName: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 14 },
  failureCheck: { alignItems: 'center', backgroundColor: theme.surfaceElevated, borderRadius: 19, height: 38, justifyContent: 'center', width: 38 },
  failureChecked: { backgroundColor: theme.primary },
  headerText: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: compact ? 10 : 11, textAlign: 'center' },
  iconHeader: { width: compact ? 44 : 48 },
  iconTouch: { alignItems: 'center', height: 46, justifyContent: 'center', width: compact ? 44 : 48 },
  input: { backgroundColor: theme.surfaceElevated, borderRadius: 8, color: theme.textPrimary, fontFamily: 'Inter', fontSize: 15, height: 46, minWidth: compact ? 52 : 58, paddingHorizontal: 5, textAlign: 'center' },
  metricHeader: { minWidth: compact ? 52 : 58 },
  planSummary: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 11, marginTop: 2 },
  readyToConfirm: { borderColor: theme.primary, borderWidth: 2 },
  removeButton: { alignSelf: 'center', justifyContent: 'center', minHeight: 38 },
  removeText: { color: theme.error, fontFamily: 'Inter-SemiBold', fontSize: 12 },
  rowError: { color: theme.error, fontFamily: 'Inter', fontSize: 11, marginLeft: compact ? 29 : 36, marginTop: 3 },
  rpeHeader: { minWidth: 52 },
  setNumber: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 12, textAlign: 'center', width: compact ? 29 : 36 },
  setRow: { alignItems: 'center', flexDirection: 'row', gap: compact ? 4 : 6, minHeight: 50 },
  startHint: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 12 },
  table: { minWidth: compact ? 330 : 354 },
  tableHeader: { alignItems: 'center', flexDirection: 'row', gap: compact ? 4 : 6, minHeight: 28 },
});
