import { StyleSheet } from 'react-native';
import { palette } from '../../constants/colors';

export const createStyles = (theme, compact = false) => StyleSheet.create({
  addSet: { alignItems: 'center', alignSelf: 'center', borderColor: theme.secondary, borderRadius: 8, borderWidth: 1, justifyContent: 'center', minHeight: 40, paddingHorizontal: 16 },
  addSetText: { color: theme.secondary, fontFamily: 'Inter-SemiBold', fontSize: 13 },
  card: { backgroundColor: theme.cardBackground, borderRadius: 9, borderWidth: 1, overflow: 'hidden' },
  cardBody: { gap: 10, padding: 10, paddingTop: 0 },
  cardHeader: { alignItems: 'center', flexDirection: 'row', gap: 8, minHeight: 54, paddingHorizontal: 10 },
  cardTitleBlock: { flex: 1 },
  completeText: { color: palette.greenBright },
  confirmCheck: { alignItems: 'center', borderColor: theme.border, borderRadius: 20, borderWidth: 1, height: 38, justifyContent: 'center', width: 38 },
  confirmDisabled: { opacity: 0.45 },
  confirmed: { backgroundColor: palette.greenBright, borderColor: palette.greenBright },
  detailsButton: { alignSelf: 'flex-start', minHeight: 32, justifyContent: 'center' },
  detailsText: { color: theme.primary, fontFamily: 'Inter-SemiBold', fontSize: 12 },
  disabled: { opacity: 0.45 },
  exerciseName: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 14 },
  failureCheck: { alignItems: 'center', backgroundColor: theme.background, borderRadius: 17, height: 34, justifyContent: 'center', width: 34 },
  failureChecked: { backgroundColor: theme.primary },
  headerText: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: compact ? 11 : 12, textAlign: 'center' },
  doneHeader: { width: 50 },
  doneTouch: { alignItems: 'center', height: 46, justifyContent: 'center', width: 50 },
  failureHeader: { width: 76 },
  failureTouch: { alignItems: 'center', height: 46, justifyContent: 'center', width: 76 },
  input: { backgroundColor: theme.background, borderRadius: 4, color: theme.textPrimary, fontFamily: 'Inter', fontSize: 13, height: 44, paddingHorizontal: 5, textAlign: 'center', width: compact ? 50 : 55 },
  planSummary: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 11, marginTop: 2 },
  readyToConfirm: { borderColor: theme.primary, borderWidth: 2 },
  removeButton: { alignItems: 'center', alignSelf: 'stretch', borderColor: theme.error, borderRadius: 8, borderWidth: 1, justifyContent: 'center', minHeight: 40 },
  removeText: { color: theme.error, fontFamily: 'Inter-SemiBold', fontSize: 12 },
  rowError: { color: theme.error, fontFamily: 'Inter', fontSize: 11, marginLeft: compact ? 29 : 36, marginTop: 3 },
  repsColumn: { alignItems: 'center', justifyContent: 'center', width: 76 },
  rpeColumn: { alignItems: 'center', justifyContent: 'center', width: 55 },
  setHeader: { width: 52 },
  setNumber: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 12, textAlign: 'center', width: 52 },
  setRow: { alignItems: 'center', flexDirection: 'row', minHeight: 48 },
  startHint: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 12 },
  table: { width: 385 },
  tableHeader: { alignItems: 'center', flexDirection: 'row', minHeight: 28 },
  tableScroll: { flexGrow: 1, justifyContent: 'center' },
  weightColumn: { alignItems: 'center', justifyContent: 'center', width: 76 },
});
