import { StyleSheet } from 'react-native';

export const createStyles = (theme) => StyleSheet.create({
  periodRow: { alignItems: 'center', flexDirection: 'row', gap: 7, paddingRight: 4 },
  periodChip: { alignItems: 'center', backgroundColor: theme.cardBackground, borderRadius: 9, justifyContent: 'center', minHeight: 36, paddingHorizontal: 13 },
  periodChipActive: { backgroundColor: theme.primary },
  periodText: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 12 },
  periodTextActive: { color: theme.onPrimary },
  calendarButton: { alignItems: 'center', borderRadius: 9, height: 36, justifyContent: 'center', width: 38 },
  calendarButtonActive: { backgroundColor: theme.primary },
  rangeLabel: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 12, marginTop: 10 },
  overlay: { alignItems: 'center', backgroundColor: theme.overlay, flex: 1, justifyContent: 'center', padding: 20 },
  modal: { backgroundColor: theme.surfaceElevated, borderRadius: 14, gap: 12, maxWidth: 420, padding: 18, width: '100%' },
  modalTitle: { color: theme.textPrimary, fontFamily: 'Inter-Bold', fontSize: 16 },
  hint: { color: theme.textSecondary, fontFamily: 'Inter', fontSize: 12, lineHeight: 17 },
  monthHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  monthTitle: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 14 },
  arrow: { alignItems: 'center', height: 40, justifyContent: 'center', width: 40 },
  weekRow: { flexDirection: 'row' },
  weekday: { color: theme.textSecondary, flex: 1, fontFamily: 'Inter-SemiBold', fontSize: 10, textAlign: 'center' },
  grid: { flexDirection: 'row', flexWrap: 'wrap' },
  day: { alignItems: 'center', borderRadius: 18, height: 38, justifyContent: 'center', width: '14.285%' },
  daySelected: { backgroundColor: theme.primary },
  dayText: { color: theme.textPrimary, fontFamily: 'Inter', fontSize: 12 },
  dayTextSelected: { color: theme.onPrimary, fontFamily: 'Inter-SemiBold' },
  disabled: { opacity: 0.35 },
  disabledText: { color: theme.textSecondary, opacity: 0.4 },
  actions: { flexDirection: 'row', gap: 10, justifyContent: 'flex-end' },
  action: { alignItems: 'center', minHeight: 44, justifyContent: 'center', paddingHorizontal: 16 },
  cancel: { color: theme.textPrimary, fontFamily: 'Inter-SemiBold', fontSize: 13 },
  apply: { alignItems: 'center', backgroundColor: theme.primary, borderRadius: 9, justifyContent: 'center', minHeight: 44, paddingHorizontal: 18 },
  applyText: { color: theme.onPrimary, fontFamily: 'Inter-Bold', fontSize: 13 },
});
